package terminal

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// ExportCLI generates CLI wrapper scripts for all tools.
func ExportCLI(w io.Writer, cliPort, mcpPort int) {
	host := "127.0.0.1"
	port := cliPort
	if port == 0 {
		port = mcpPort
	}
	baseURL := fmt.Sprintf("http://%s:%d", host, port)
	cliDir := filepath.Join(".", "cli")
	_ = os.MkdirAll(cliDir, 0o755)

	// List of tools to generate wrappers for (excluding context, matching TS)
	toolNames := []string{
		"browser", "capture", "codegraph", "colab",
		"memory", "memory_isolate", "memory_shared",
		"run", "shell", "skill", "think", "ui-vision", "workspace",
	}

	generated := 0
	for _, tool := range toolNames {
		script := buildWrapperScript(tool, baseURL)
		path := filepath.Join(cliDir, "zen-"+tool)
		_ = os.WriteFile(path, []byte(script), 0o755)
		generated++
	}

	fmt.Fprintf(w, "Exported %d tools → %s\n", generated, cliDir)
}

// ExportCliClean removes generated CLI wrappers.
func ExportCliClean(w io.Writer) {
	cliDir := filepath.Join(".", "cli")
	entries, _ := os.ReadDir(cliDir)
	removed := 0
	for _, entry := range entries {
		if entry.Name()[0:4] == "zen-" {
			_ = os.Remove(filepath.Join(cliDir, entry.Name()))
			removed++
		}
	}
	fmt.Fprintf(w, "Cleaned %d zen-* artifacts from %s\n", removed, cliDir)
}

func buildWrapperScript(tool, baseURL string) string {
	return fmt.Sprintf(`#!/bin/bash
# Auto-generated by zen-mcp export-cli
# Tool: %s
URL="%s/mcp"
HEADER="Content-Type: application/json"
ACTION="${1:-}"
JSON_ARGS="${2:-{}}"

if [ -z "$ACTION" ]; then
  echo "Usage: zen-%s --action <action> [--json <args>]"
  exit 1
fi

PAYLOAD=$(cat <<EOF
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "tools/call",
  "params": {
    "name": "%s",
    "arguments": {
      "action": "$ACTION"
    }
  }
}
EOF
)

curl -s -X POST "$URL" \
  -H "$HEADER" \
  -H "x-workspace-root: $(pwd)" \
  -d "$PAYLOAD" | python3 -m json.tool 2>/dev/null || curl -s -X POST "$URL" -H "$HEADER" -H "x-workspace-root: $(pwd)" -d "$PAYLOAD"
`, tool, baseURL, tool, tool)
}
